"""Initial schema

Revision ID: 2e9ac00d4a54
Revises:
Create Date: 2026-02-05 02:32:31.294933

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2e9ac00d4a54"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
